version: "3.8"

services:
  neo4j:
    hostname: neo4j
    image: neo4j:latest
    restart: always
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - .neo4j_data:/data
    environment:
      NEO4J_AUTH: neo4j/password
