[tool.poetry]
name = "neo4j-ogm"
version = "0.1.0"
description = ""
authors = ["groc-prog <marc.troisner@gmail.com>"]
readme = "README.md"
packages = [{include = "neo4j_ogm"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.9"
neo4j = "^5.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"


[tool.pyright]
reportGeneralTypeIssues = false


[tool.pylint.messages_control]
disable = "no-self-argument"
