[tool.poetry]
name = "neo4j-ogm"
version = "0.1.0"
description = ""
authors = ["groc-prog <marc.troisner@gmail.com>"]
readme = "README.md"
packages = [{include = "neo4j_ogm"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
