name: Formatting and linting checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyright:
    name: Run pyright type-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.5.1"
      - name: Setup local virtual environment
        run: poetry config virtualenvs.create true --local && poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Create cache for the virtual environment
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install project dependencies
        run: poetry install
      - name: Run pyright
        run: poetry run pyright

  pylint:
    name: Run pylint linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.5.1"
      - name: Setup local virtual environment
        run: poetry config virtualenvs.create true --local && poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Create cache for the virtual environment
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install project dependencies
        run: poetry install
      - name: Run pylint
        run: poetry run pylint --rcfile=.pylintrc neo4j_ogm tests
