name: Quality checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  type-checker:
    name: Run type-checker
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11.5"
      POETRY_VERSION: "1.5.1"
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry ${{ env.POETRY_VERSION }}
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - name: Setup a local virtual environment
        run: poetry config virtualenvs.create true --local && poetry config virtualenvs.in-project true --local
      - name: Install dependencies
        run: poetry install
      - name: Run type-checker
        run: poetry run pyright

  linter:
    name: Run linter
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11.5"
      POETRY_VERSION: "1.5.1"
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry ${{ env.POETRY_VERSION }}
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - name: Setup a local virtual environment
        run: poetry config virtualenvs.create true --local && poetry config virtualenvs.in-project true --local
      - name: Install dependencies
        run: poetry install
      - name: Run linter
        run: poetry run pylint --rcfile=.pylintrc pyneo4j_ogm tests
