name: Package release

on:
  workflow_run:
    workflows: [checks]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [quality, tests]
    steps:
      - name: foo
        run: echo "foo"
